# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- backup.appuio.ch_schedules.yaml
- backup.appuio.ch_backups.yaml
- backup.appuio.ch_restores.yaml
- backup.appuio.ch_archives.yaml
- backup.appuio.ch_checks.yaml
- backup.appuio.ch_prunes.yaml
- backup.appuio.ch_snapshots.yaml
- backup.appuio.ch_prebackuppods.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_schedules.yaml
#- patches/webhook_in_backups.yaml
#- patches/webhook_in_restores.yaml
#- patches/webhook_in_archives.yaml
#- patches/webhook_in_checks.yaml
#- patches/webhook_in_prunes.yaml
#- patches/webhook_in_snapshots.yaml
#- patches/webhook_in_prebackuppods.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_schedules.yaml
#- patches/cainjection_in_backups.yaml
#- patches/cainjection_in_restores.yaml
#- patches/cainjection_in_archives.yaml
#- patches/cainjection_in_checks.yaml
#- patches/cainjection_in_prunes.yaml
#- patches/cainjection_in_snapshots.yaml
#- patches/cainjection_in_prebackuppods.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
