image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY: "registry.vshn.net"
  IMAGE_NAME: "vshn/baas"
  IMAGE_NAME_DOCKER_HUB: "appuio/baas"

.dockerbuild: &dockerbuild
  script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
    - docker build .
        -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
        -t docker.io/${IMAGE_NAME_DOCKER_HUB}:${IMAGE_TAG}
    - docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    - docker push docker.io/${IMAGE_NAME_DOCKER_HUB}:${IMAGE_TAG}

build:dev:
  variables:
    IMAGE_TAG: dev
  <<: *dockerbuild
  tags:
    - dockerbuild
  only:
    - dev

build:latest:
  variables:
    IMAGE_TAG: latest
  <<: *dockerbuild
  tags:
    - dockerbuild
  only:
    - master

build:tag:
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  <<: *dockerbuild
  only:
    - tags
  tags:
    - dockerbuild
