image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY: "registry.vshn.net"
  IMAGE_NAME: "vshn/baas"
  IMAGE_NAME_DOCKER_HUB: "appuio/baas"

before_script:
- docker info
- echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $REGISTRY
- echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin

build:
  script:
    - docker build -t ${REGISTRY}/${IMAGE_NAME} .
    - docker tag ${REGISTRY}/${IMAGE_NAME} docker.io/${IMAGE_NAME_DOCKER_HUB}
    - docker push ${REGISTRY}/${IMAGE_NAME}
    - docker push docker.io/${IMAGE_NAME_DOCKER_HUB}
  tags:
    - dockerbuild
  only:
    - master

build:tag:
  script:
    - docker build -t ${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker tag ${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG} docker.io/${IMAGE_NAME_DOCKER_HUB}:${CI_COMMIT_TAG}
    - docker push ${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push docker.io/${IMAGE_NAME_DOCKER_HUB}:${CI_COMMIT_TAG}
  only:
    - tags
  tags:
    - dockerbuild
