language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME="docker.io/${TRAVIS_REPO_SLUG}"

before_script:
  - docker info
  - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin

script:
  - docker build . -t ${IMAGE_NAME}:${IMAGE_TAG}

deploy:
  # Merging the master/dev conditions like "branch =~ /(master|dev)/" does not work,
  # Travis would always skip it with "Skipping a deployment with the script provider
  # because a custom condition was not met", even though this is 1:1 from official
  # documentation
  - provider: script
    script: docker push ${IMAGE_NAME}:${IMAGE_TAG}
    on:
      branch: dev
  - provider: script
    script: docker push ${IMAGE_NAME}:${IMAGE_TAG}
    on:
      branch: master
  - provider: script
    script: docker push ${IMAGE_NAME}:${IMAGE_TAG}
    on:
      tags: true

jobs:
  include:
    - if: branch = dev
      env:
        - IMAGE_TAG=dev

    - if: branch = master
      env:
        - IMAGE_TAG=latest

    - if: tag IS present
      env:
        - IMAGE_TAG="${TRAVIS_TAG}"
