apiVersion: v2
description: Kubernetes and OpenShift Backup Operator based on restic
name: k8up
home: https://k8up.io/
keywords:
  - backup
  - operator
  - restic
version: 2.0.5
appVersion: v2.3.2
sources:
  - https://github.com/k8up-io/k8up
maintainers:
  - name: APPUiO Team
    email: info@appuio.ch
