apiVersion: v2
description: Kubernetes and OpenShift Backup Operator based on restic
name: k8up
home: https://k8up.io/
keywords:
  - backup
  - operator
  - restic
version: 4.4.4
sources:
  - https://github.com/k8up-io/k8up
maintainers:
  - name: K8up Authors
    email: info@appuio.ch
