---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-test
spec:
  resourceRequirementsTemplate:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio.minio:9000
      bucket: k8up
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
  archive:
    schedule: '0 * * * *'
    restoreMethod:
      s3:
        endpoint: http://minio.minio:9000
        bucket: restoremini
        accessKeyIDSecretRef:
          name: backup-credentials
          key: username
        secretAccessKeySecretRef:
          name: backup-credentials
          key: password
  backup:
    schedule: '*/2 * * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    promURL: http://minio.minio:9000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "1000m"
  check:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
    schedule: '@hourly-random'
    promURL: http://minio.minio:9000
  prune:
    schedule: '*/4 * * * *'
    retention:
      keepLast: 5
      keepDaily: 14
